# Generated by Django 5.2.3 on 2025-07-14 10:46

import api.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(storage=api.storages.AudioCloudinaryStorage(), upload_to='episodes/'),
        ),
    ]
