# Generated by Django 5.2.3 on 2025-07-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_episode_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(upload_to='episodes/'),
        ),
    ]
