# Generated by Django 5.2.3 on 2025-07-14 11:11

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_episode_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=api.fields.AudioFileField(storage=api.fields.AudioCloudinaryStorage(), upload_to='episodes/'),
        ),
    ]
