version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: podcast_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=podcast
      - POSTGRES_USER=podcast_user
      - POSTGRES_PASSWORD=podcast_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U podcast_user -d podcast"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
